name: Kernel Build Workflow 

on:
  pull_request:
  workflow_dispatch:
    inputs:
      KERNEL_TREE:
        description: 'Kernel Tree'
        default: 'https://github.com/Sayemx18/kernel_xiaomi_sm8250.git'
        required: true
      BRANCH:
        description: 'Branch'
        default: 'base'
        required: true
      ANYKERNEL_URL:
        description: 'AnyKernel Url (leave blank if you dont want AnyKernel)'
        default: 'https://github.com/Sayemx18/AnyKernel3.git'
        required: false
      COMPILER:
        description: 'Choose compiler'
        required: true
        type: choice
        options:
          - neutron
          - aosp
          - aosp-21
        default: aosp
      
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      UPLOAD_TO_RELEASE: false

    steps:
      - name: Install Dependencies
        run: sudo apt install flex libncurses6

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: kernel-build-${{ github.event.inputs.COMPILER }}-${{ github.sha }}
          restore-keys: |
            kernel-build-${{ github.event.inputs.COMPILER }}-
            kernel-build-
          max-size: 3G

      - name: Cache Clang Toolchain
        id: cache-toolchain
        uses: actions/cache@v4
        with:
          path: toolchain
          key: toolchain-${{ github.event.inputs.COMPILER }}-v1

      - name: Download & Extract Clang
        if: steps.cache-toolchain.outputs.cache-hit != 'true'
        run: |
          if [[ "${{ github.event.inputs.COMPILER }}" == "aosp" ]]; then
            wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r547379.tar.gz -O clang.tar.gz
            mkdir toolchain
            tar -xf clang.tar.gz -C toolchain
          elif [[ "${{ github.event.inputs.COMPILER }}" == "aosp-21" ]]; then
            wget clang-r574158.tar.gz -O clang.tar.gz
            mkdir toolchain
            tar -xf clang.tar.gz -C toolchain
          else
            wget https://github.com/Neutron-Toolchains/clang-build-catalogue/releases/download/10032024/neutron-clang-10032024.tar.zst -O clang.tar.zst
            mkdir toolchain
            unzstd -d clang.tar.zst
            tar -xf clang.tar -C toolchain
          fi      

      - name: Clone Repo
        run: |
          git clone --depth=1 --recurse-submodules ${{ github.event.inputs.KERNEL_TREE }} -b ${{ github.event.inputs.BRANCH }} Redlines
        
      - name: Build Kernel
        run: |
          export PATH="$(pwd)/toolchain/bin:$PATH"
          export ARCH=arm64
          export SUBARCH=ARM64
          export KBUILD_BUILD_USER="sayem"
          export KBUILD_BUILD_HOST="Sayemx18"
          export KBUILD_BUILD_TIMESTAMP="$(TZ=UTC-7 date)"
          export USE_CCACHE=1
          export CCACHE_EXEC=/usr/bin/ccache
          cd Redlines
          make O=out alioth_defconfig \
          vendor/xiaomi/raikiri-common.config
          grep THERMAL_DIMMING out/.config
          grep FAKE_UNAME_5_15=y out/.config
          make O=out \
            ARCH=arm64 \
            SUBARCH=arm64 \
            LLVM=1 \
            LLVM_IAS=1 \
            CC="ccache clang" \
            HOSTCC=clang \
            HOSTCXX=clang++ \
            CROSS_COMPILE=aarch64-linux-gnu- \
            CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
            CLANG_TRIPLE=aarch64-linux-gnu- \
            -j$(nproc --all) \
            2>&1 | tee out/build.log
          find out/arch/arm64/boot/dts -name '*.dtb' -exec cat {} + >out/arch/arm64/boot/dtb

      - name: Upload Images
        uses: actions/upload-artifact@v4
        with:
          name: kernel-artifacts
          path: |
            ./Redlines/out/arch/arm64/boot/Image
            ./Redlines/out/arch/arm64/boot/dtb
            ./Redlines/out/arch/arm64/boot/dtbo.img
            ./Redlines/out/build.log
          if-no-files-found: ignore
          retention-days: 7
           
      - name: Clone AnyKernel3
        run: git clone --recursive --depth=1 ${{ github.event.inputs.ANYKERNEL_URL }} -b main anykernel

      - name: Move Kernel Files to AnyKernel3
        run: |
          mv ./Redlines/out/arch/arm64/boot/Image anykernel/
          mv ./Redlines/out/arch/arm64/boot/dtb anykernel/
          mv ./Redlines/out/arch/arm64/boot/dtbo.img anykernel/

      - name: Define ZIP Name
        run: |
          COMPILED_DATE=$(date +%Y%m%d)
          echo "ZIP_NAME=Raikiri-v1.0-alioth(KSU)-${COMPILED_DATE}" >> $GITHUB_ENV
          
      - name: Create Flashable Kernel Zip
        run: |
          cd anykernel
          zip -r "../${ZIP_NAME}.zip" . -x ".git/*" ".github/*"
          
      - name: Upload Flashable Kernel Zip
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ZIP_NAME }}
          path: ${{ env.ZIP_NAME }}.zip
          retention-days: 30
          
#      - name: Upload Kernel Zip to Telegram
  #      env:
       #   TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
    #      TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
#        run: |
         # CAPTION="This is Raikiri Kernel For alioth
   #       add -5k in the Zip name if you have 5kmah battery
       #   Thin Lto
   #       Support Ksu-next v3.x.x
   #       Changelog:Latest changes from Los
   #       kerrnel Source: https://github.com/Sayemx18/kernel_xiaomi_sm8250"

    #      curl -s -X POST "https://api.telegram.org/bot${TG_BOT_TOKEN}/sendDocument" \
     #       -F chat_id="${TG_CHAT_ID}" \
      #      -F document=@"${ZIP_NAME}.zip" \
       #     -F caption="$CAPTION"
      
