name: sayem kernel

on:
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Kernel Source
        run: |
          git clone --depth=1 https://github.com/Sayemx18/arrow_kernel_alioth -b upstream kernel_tree


      - name: Download AOSP Clang
        run: |
          wget -q https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/mirror-goog-main-llvm-toolchain-source/clang-r574158.tar.gz
          mkdir -p aosp-clang
          tar -xzf clang-r574158.tar.gz -C aosp-clang

      - name: Build kernel
        run: |
          
          cd kernel_tree
          
          curl -LSs "https://raw.githubusercontent.com/rsuntk/KernelSU/main/kernel/setup.sh" | bash -s main
          chmod +x scripts/Compiler/compiler.sh
          scripts/Compiler/compiler.sh \
            DEFCONFIG=alioth_defconfig \
            CLANG_DIR=$PWD/aosp-clang \
            KBUILD_BUILD_USER=Sayem \
            KBUILD_BUILD_HOST=Sayemx18

      - name: Upload Image & DTBO
        uses: actions/upload-artifact@v4
        with:
          name: RedlineKernel-Alioth
          path: |
            out/arch/arm64/boot/Image
            out/arch/arm64/boot/dtb.img
            out/arch/arm64/boot/dtbo.img

      - name: Upload log
        uses: actions/upload-artifact@v4
        with:
          name: compile-log
          path: out/compile.log
