name: Alioth Kernel Matrix Build

on:
  workflow_dispatch:
    inputs:
      COMPILER:
        description: Choose compiler
        type: choice
        required: true
        default: aosp
        options:
          - aosp
          - aosp-21
          - neutron
          - zyc

      ANYKERNEL_URL:
        default: https://github.com/Sayemx18/AnyKernel3.git
        required: true

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        variant: [aosp, miui, aosp5k, miui5k]

    steps:
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y flex libncurses6 bc ccache git wget tar xz-utils zstd
        
      - name: Build (${{ matrix.variant }})
        run: |
          chmod +x build.sh
          COMPILER=${{ inputs.COMPILER }} \
          KERNEL_VARIANT=${{ matrix.variant }} \
          bash build.sh

      - name: Upload Kernel Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-${{ matrix.variant }}
          path: out_artifacts/${{ matrix.variant }}/

  package:
    needs: build
    runs-on: ubuntu-22.04

    steps:
      - name: Download all kernel builds
        uses: actions/download-artifact@v4
        with:
          path: kernels

      - name: Clone AnyKernel3
        run: git clone --depth=1 ${{ inputs.ANYKERNEL_URL }} AnyKernel3

      - name: Merge all variants safely
        run: |
          cp kernels/kernel-aosp/* AnyKernel3/
          cp kernels/kernel-miui/* AnyKernel3/
          cp kernels/kernel-aosp5k/* AnyKernel3/
          cp kernels/kernel-miui5k/* AnyKernel3/

      - name: Create flashable zip
        run: |
          DATE=$(date +%Y%m%d)
          cd AnyKernel3
          zip -r ../Raikiri-v1.1-alioth-$DATE.zip . -x ".git/*" ".github/*"

      - name: Upload final AnyKernel zip
        uses: actions/upload-artifact@v4
        with:
          name: Raikiri-alioth-v1.1
          path: Raikiri-v1.1-alioth-*.zip
