name: Redline-fork ksu

on:
  pull_request:
  workflow_dispatch:
    inputs:
      KERNEL_TREE:
        description: 'Kernel Tree'
        default: 'https://github.com/PocoF3Releases/kernel_xiaomi_sm8250.git'
        required: true
      ANYKERNEL_URL:
        description: 'AnyKernel Url (leave blank if you dont want AnyKernel)'
        default: 'https://github.com/Sayemx18/AnyKernel3.git'
        required: false
      COMPILER:
        description: 'Choose compiler'
        required: true
        type: choice
        options:
          - neutron
          - aosp
          - aosp-21
        default: aosp

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      UPLOAD_TO_RELEASE: false

    steps:
      - name: Install Dependencies
        run: sudo apt install flex libncurses6

      - name: Download & Extract Clang
        run: |
          if [[ "${{ github.event.inputs.COMPILER }}" == "aosp" ]]; then
            wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r547379.tar.gz -O clang.tar.gz
            mkdir clang
            tar -xf clang.tar.gz -C clang
          elif [[ "${{ github.event.inputs.COMPILER }}" == "aosp-21" ]]; then
            wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/ebcc6c3bef363bc539ea39f45b6abae1dce6ff1a/clang-r574158.tar.gz -O clang.tar.gz
            mkdir clang
            tar -xf clang.tar.gz -C clang
          else
            wget https://github.com/Neutron-Toolchains/clang-build-catalogue/releases/download/10032024/neutron-clang-10032024.tar.zst -O clang.tar.zst
            mkdir clang
            unzstd -d clang.tar.zst
            tar -xf clang.tar -C clang
          fi

      - name: Clone Repo
        run: |
          git clone ${{ github.event.inputs.KERNEL_TREE }} RedlineFork

      - name: Lets cherry-pick
        run : | 
          git config --global user.email "sayemxx18@gmail.com"
          git config --global user.name "sayem"
          cd RedlineFork
          git remote add mymods https://github.com/Sayemx18/kernel_xiaomi_sm8250.git
          git fetch mymods
          git cherry-pick 88667341c364a7ba711085491fe57e2a803af76a^..23728680189d42a5ffbbfddd2670d20c9fae588a
          git cherry-pick 8ece70fba1d93fe623c6df4309afda4dd113d55f^..a852125b89f871fdf6a82fba34b8f2733eff0f79
          git fetch origin
          git revert 1cdb6ca2c3ef5de1d2e3b0955dea40add27c2749
          git revert bc1c8973e55c9aee9446fd493bffeb47a1e848f6

      - name: Build Kernel
        run: |
          export PATH="$(pwd)/clang/bin:$PATH"
          export ARCH=arm64
          export SUBARCH=ARM64
          export KBUILD_BUILD_USER="sayem"
          export KBUILD_BUILD_HOST="Sayemx18"
          export KBUILD_BUILD_TIMESTAMP="$(TZ=UTC-7 date)"
          cd RedlineFork
          git submodule update --init --recursive
          make O=out alioth_defconfig
          make O=out CC=clang -j$(nproc --all) CROSS_COMPILE=aarch64-linux-gnu- LLVM=1 LLVM_IAS=1
          find out/arch/arm64/boot/dts -name '*.dtb' -exec cat {} + >out/arch/arm64/boot/dtb
          echo "all files:"
          ls -lhaR out/arch/arm64/boot/

      - name: Upload Image
        uses: actions/upload-artifact@v4
        with:
          name: Image
          path: ./RedlineFork/out/arch/arm64/boot/Image
          if-no-files-found: ignore
          retention-days: 7
      
      - name: Upload dtb
        uses: actions/upload-artifact@v4
        with:
          name: dtb
          path: ./RedlineFork/out/arch/arm64/boot/dtb
          if-no-files-found: ignore
          retention-days: 7

      - name: Upload dtbo.img
        uses: actions/upload-artifact@v4
        with:
          name: dtbo.img
          path: ./RedlineFork/out/arch/arm64/boot/dtbo.img
          if-no-files-found: ignore
          retention-days: 7
          
      - name: Clone AnyKernel3
        run: git clone --recursive --depth=1 ${{ github.event.inputs.ANYKERNEL_URL }} -b main anykernel

      - name: Move Kernel Files to AnyKernel3
        run: |
          mv ./RedlineFork/out/arch/arm64/boot/Image anykernel/
          mv ./RedlineFork/out/arch/arm64/boot/dtb anykernel/
          mv ./RedlineFork/out/arch/arm64/boot/dtbo.img anykernel/

      - name: Define ZIP Name
        run: |
          COMPILED_DATE=$(date +%Y%m%d)
          echo "ZIP_NAME=Redline-Fork(KSU)-${COMPILED_DATE}" >> $GITHUB_ENV
          
      - name: Create Flashable Kernel Zip
        run: |
          cd anykernel
          zip -r "../${ZIP_NAME}.zip" . -x ".git/*" ".github/*"
          
      - name: Upload Flashable Kernel Zip
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ZIP_NAME }}
          path: ${{ env.ZIP_NAME }}.zip
          retention-days: 30
          
      - name: Upload Kernel Zip to Telegram
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          CAPTION="Redline Fork Kernel For alioth
          Battery Variant: Stock
          Kernel Source: https://github.com/Sayemx18/kernel_xiaomi_sm8250"

          curl -s -X POST "https://api.telegram.org/bot${TG_BOT_TOKEN}/sendDocument" \
            -F chat_id="${TG_CHAT_ID}" \
            -F document=@"${ZIP_NAME}.zip" \
            -F caption="$CAPTION"
      
